    let baseQuery limitOffsetOrder = from $ \(~{selectVar} ~{concatMap joinDef (sqJoins sq)}) -> do
~{indent 8 $ joinExprs}        let ~{selectVar}Id' = ~{selectVar} ^. ~{entityRefName selectEntity}Id
~{indent 8 $ maybeWhere}
        _ <- when limitOffsetOrder $ do
            offset ~{show offset}
            limit ~{show limit}
~{indent 12 $ maybeDefaultSortFields}
~{indent 12 $ maybeDefaultLimitOffset}                 
