                "~{alias}" -> case FS.f_value fjm of
                    Just value -> case PP.fromPathPiece value of 
                            (Just v') -> where_ $ defaultFilterOp (FS.f_negate fjm) (FS.f_comparison fjm) (~{vn} ~{projectField isMaybe} ~{entityFieldTypeName e f}) (~{makeJust maybeLevel "(val v')"})
                            _        -> return ()
                    Nothing -> where_ $ defaultFilterOp (FS.f_negate fjm) (FS.f_comparison fjm) (~{vn} ~{projectField isMaybe} ~{entityFieldTypeName e f}) nothing
                           
