    attr_~{fn} <- do
        mv <- lookupGetParam "~{fn}"
        case mv of
            Just v -> case PP.fromPathPiece v of
                Just v' -> return v'
                Nothing -> sendResponseStatus status400 $ A.object [
                        "message" .= ("Could not parse value from the parameter ~{fn} in the query string" :: Text),
                        "error ".= ("Parse error" :: Text)
                    ]
            Nothing -> return $ ~{fieldValueToHs d}
