instance ToJSON Day where
    toJSON = toJSON . show

instance FromJSON Day where
    parseJSON x = do
        s <- parseJSON x
        case reads s of
            (d, _):_ -> return d
            [] -> mzero 

newtype JSONWrapper a = JSONWrapper a  

instance ToJSON (JSONWrapper (Entity k v)) where
    toJSON (JSONWrapper (Entity k v)) = case toJSON v of
        Object o -> Object $ HML.insert "id" (toJSON k) o
        _ -> eror "unexpected JS encode error"
